### ISSUE TITLE
Owlet server update

### ISSUE THREAD

**Issue by jareware** [mbevand/owlet_monitor#2]
Hey @mbevand,

Just on the off-chance you're still using this yourself: did you notice the script breaking with the recent (as in 3 days ago or so) server update?

**Comment by mbevand** [comment]
Sorry I no longer use my script. I don't even have the Owlet anymore. My daughter grew up :)

**Comment by jareware** [comment]
Heh, that's pretty much what I expected. :)

I fixed it for myself and sent a PR to this repo, just so it's documented somewhere (#3).

Thanks again for doing the original work, it's been super nice!
